"""deleting-tracksid-from-albums

Revision ID: a639c7a44f25
Revises: 2cf15cc1ce3f
Create Date: 2024-06-30 16:27:39.643062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a639c7a44f25'
down_revision: Union[str, None] = '2cf15cc1ce3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'tracks_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('tracks_id', sa.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
